apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vnshop-ingress
  namespace: vnshop
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vnshop.example.com
      secretName: vnshop-tls
  rules:
    - host: vnshop.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vnshop-api-gateway
                port:
                  number: 8080
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8085
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
