server:
  port: 8086

spring:
  application:
    name: search-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vnshop?currentSchema=search_svc
    username: vnshop
    password: vnshop
  flyway:
    enabled: true
    schemas: search_svc
    default-schema: search_svc
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/vnshop}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
