server:
  port: 8088
spring:
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/vnshop}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/vnshop/protocol/openid-connect/certs}
  datasource:
    url: jdbc:postgresql://localhost:5432/vnshop?currentSchema=coupon_svc
    username: vnshop
    password: ${DB_PASSWORD:vnshop123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: coupon-svc-pool
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:vnshop123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
      group:
        readiness:
          include: readinessState,db
        liveness:
          include: livenessState
