server:
  port: 8088
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vnshop?currentSchema=coupon_svc
    username: vnshop
    password: ${DB_PASSWORD:vnshop123}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:vnshop123}
