server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vnshop?currentSchema=coupon_svc
    username: vnshop
    password: vnshop123
  jpa:
    hibernate:
      ddl-auto: update
