package com.vnshop.invoiceservice.application.gdt;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.vnshop.invoiceservice.domain.entity.Invoice;
import com.vnshop.invoiceservice.domain.entity.InvoiceStatus;
import com.vnshop.invoiceservice.domain.repository.InvoiceRepository;
import jakarta.persistence.EntityNotFoundException;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Orchestrates submission of e-invoice XML payloads to the GDT API and
 * persists the resulting acceptance / rejection state on the invoice.
 *
 * <p>All submitted XML payloads are preserved permanently on the invoice entity
 * to satisfy the 10-year retention obligation under Vietnamese e-invoice regulations.</p>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class InvoiceSubmissionService {

    private final InvoiceRepository invoiceRepository;
    private final GdtApiClient gdtApiClient;
    private final ObjectMapper objectMapper;

    /**
     * Submits the invoice for the given orderId to the GDT API.
     * The invoice must already have an {@code xmlPayload} (generated by Track 7.2).
     *
     * @param orderId the order whose invoice should be submitted
     * @return the updated invoice after GDT response is persisted
     * @throws EntityNotFoundException      if no invoice exists for the orderId
     * @throws IllegalStateException        if the invoice has no XML payload yet
     */
    @Transactional
    public Invoice submitToGdt(UUID orderId) {
        Invoice invoice = loadAndValidate(orderId);
        return doSubmit(invoice);
    }

    /**
     * Resubmits a previously REJECTED invoice after admin correction.
     * The invoice must be in REJECTED status with an updated xmlPayload.
     *
     * @param orderId the order whose invoice should be resubmitted
     * @return the updated invoice after GDT response is persisted
     */
    @Transactional
    public Invoice resubmitToGdt(UUID orderId) {
        Invoice invoice = loadAndValidate(orderId);
        if (invoice.getStatus() != InvoiceStatus.REJECTED) {
            throw new IllegalStateException(
                    "Only REJECTED invoices may be resubmitted; current status=" + invoice.getStatus());
        }
        log.info("Resubmitting REJECTED invoice id={} orderId={}", invoice.getId(), orderId);
        return doSubmit(invoice);
    }

    private Invoice doSubmit(Invoice invoice) {
        log.info("Submitting invoice id={} orderId={} to GDT", invoice.getId(), invoice.getOrderId());

        invoice.setStatus(InvoiceStatus.SUBMITTED);
        invoice.setSubmittedAt(Instant.now());
        invoice.setUpdatedAt(Instant.now());
        invoiceRepository.save(invoice);

        GdtSubmissionResult result = gdtApiClient.submitInvoice(invoice.getXmlPayload());

        invoice.setGdtResponseJson(toJson(result));
        invoice.setUpdatedAt(Instant.now());

        if (result.success()) {
            invoice.setStatus(InvoiceStatus.ACCEPTED);
            invoice.setGdtInvoiceNumber(result.gdtInvoiceNumber());
            invoice.setGdtVerificationCode(result.verificationCode());
            log.info("Invoice id={} ACCEPTED by GDT: invoiceNumber={} verificationCode={}",
                    invoice.getId(), result.gdtInvoiceNumber(), result.verificationCode());
        } else {
            invoice.setStatus(InvoiceStatus.REJECTED);
            invoice.setRejectionReason(result.rejectionReason());
            log.warn("Invoice id={} REJECTED by GDT: reason={}", invoice.getId(), result.rejectionReason());
        }

        return invoiceRepository.save(invoice);
    }

    private Invoice loadAndValidate(UUID orderId) {
        Invoice invoice = invoiceRepository.findByOrderId(orderId)
                .orElseThrow(() -> new EntityNotFoundException("No invoice found for orderId=" + orderId));
        if (invoice.getXmlPayload() == null || invoice.getXmlPayload().isBlank()) {
            throw new IllegalStateException(
                    "Invoice id=" + invoice.getId() + " has no XML payload — generate XML first");
        }
        return invoice;
    }

    private String toJson(GdtSubmissionResult result) {
        try {
            return objectMapper.writeValueAsString(Map.of(
                    "success", result.success(),
                    "gdtInvoiceNumber", result.gdtInvoiceNumber() != null ? result.gdtInvoiceNumber() : "",
                    "verificationCode", result.verificationCode() != null ? result.verificationCode() : "",
                    "rejectionReason", result.rejectionReason() != null ? result.rejectionReason() : ""
            ));
        } catch (JsonProcessingException e) {
            log.warn("Failed to serialise GdtSubmissionResult to JSON", e);
            return "{}";
        }
    }
}
