grpc:
  client:
    inventory:
      host: ${GRPC_CLIENT_INVENTORY_HOST:localhost}
      port: ${GRPC_CLIENT_INVENTORY_PORT:9093}
    payment:
      host: ${GRPC_CLIENT_PAYMENT_HOST:localhost}
      port: ${GRPC_CLIENT_PAYMENT_PORT:9094}
    shipping:
      host: ${GRPC_CLIENT_SHIPPING_HOST:localhost}
      port: ${GRPC_CLIENT_SHIPPING_PORT:9095}
