apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: vnshop-istio
  namespace: istio-system
spec:
  profile: minimal
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      tracing:
        zipkin:
          address: jaeger.vnshop.svc.cluster.local:9411
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
