apiVersion: v1
kind: Secret
metadata:
  name: vnshop-app-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: vnshop
  SPRING_DATASOURCE_PASSWORD: change-me
  DB_USERNAME: vnshop
  DB_PASSWORD: change-me
  GATEWAY_OAUTH2_CLIENT_SECRET: change-me
