KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret-change-me"
    user_admin="admin-secret-change-me"
    user_svc-order="order-secret-change-me"
    user_svc-payment="payment-secret-change-me"
    user_svc-inventory="inventory-secret-change-me"
    user_svc-product="product-secret-change-me"
    user_svc-shipping="shipping-secret-change-me"
    user_svc-finance="finance-secret-change-me"
    user_svc-search="search-secret-change-me"
    user_svc-recommendations="recommendations-secret-change-me";
};
